# Generated by Django 4.2.30 on 2026-04-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
