# Generated by Django 4.2.30 on 2026-04-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='search_vector',
            field=models.TextField(blank=True, null=True),
        ),
    ]
