# Generated by Django 4.2.30 on 2026-04-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_post_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
