# Generated by Django 4.2.30 on 2026-04-19 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_userevent_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(blank=True, max_length=100)),
                ('energy', models.FloatField(default=0)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('time_of_day', models.CharField(blank=True, max_length=50)),
                ('tags', models.JSONField(default=list)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='music.post')),
            ],
        ),
    ]
