# Generated by Django 4.2.30 on 2026-04-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_post_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio_features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
