# Generated by Django 4.2.30 on 2026-04-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_post_audio_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='provider',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
