# Generated by Django 6.0.2 on 2026-03-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_notification_sub_post_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='embed_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
