# Generated by Django 6.0.2 on 2026-03-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_post_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='provider',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
